os:
  - linux
  - osx
language: c
compiler:
  - clang
  - gcc
before_install:
  - |
      if ! git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '(.md)|(.vc)|(.tc)|(.pm)|(.diff)|(.pl)|(.cmd)|(.hash)|(.cl)|(.yaml)|(.rule)|(.hckmap)|(.charset)|(.appveyor.yml)|(.editorconfig)|(.gitattributes)|(.gitignore)|(.lock)|(.hcmask)'
      then
        echo "No code changes detected, skip the CI build."
        exit
      fi
script:
  - bash -c 'shopt -s globstar nullglob; shellcheck extra/**/*.{sh,bash} && shellcheck tools/**/*.{sh,bash}' || exit
  - make
